services:
  - type: web
    name: flask-productos-alex  # Nombre único para tu servicio
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13